# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Build.SourceBranchName)_$(Rev:rr)

trigger:
  branches:
    include:
    - '*'

variables:
  dotnet_version: "8.0.x"

pool:
  name: default
  demands:
  - Agent.OS -equals Linux

steps:

- task: UseDotNet@2
  displayName: 'Install'
  inputs:
    packageType: 'sdk'
    version: $(dotnet_version)

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  displayName: 'Pack'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byBuildNumber'

- task: DotNetCoreCLI@2
  displayName: 'Upload Artifact'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: '199dbc09-2375-465c-b64d-796f8d3f742f/87f9bd7b-5e8d-4aca-a1bd-2e3de3a5eaa8'

- script: |
    echo End
  displayName: 'End'
